### ISSUE TITLE
add_ methods don't work

### ISSUE THREAD

**Issue by burbilog** [pschmitt/guacapy#31]
I tried guacapy library with three docker versions of guacamole -- guacamole/guacamole 1.1.0 (mysql), oznu/guacamole 1.1.0 (postgres), oznu/guacamole 1.0.0 (postgres). In all cases get_* methods work fine, returning data from guacamole, but add_user and others failed to perform.

~~~
#!/usr/bin/env python2

import json
import guacapy

url = ""
hostname = "host:7070"
user = "guacadmin"
passwd = "guacadmin"

# initialize guacamole connection
client = guacapy.Guacamole(url_path = url, username = user, password = passwd,    hostname = hostname,
                method='http', verify=True)

usr = client.get_user('guacadmin')
print(json.dumps(usr))

g = """{"parentIdentifier":"ROOT", "name":"iaas-099 (Test)", "type":"ORGANIZATIONAL", "attributes":{"max-connections":"","max-connections-per-user":""}}"""
client.add_connection_group(g)

u = """\
{   
    "username": "testusr",
    "password": "testpwd",
    "attributes": {
        "disabled": "",
        "expired": "",
        "access-window-start": "",
        "access-window-end": "",
        "valid-from": "",
        "valid-until": "",
        "timezone": ""
    }
}"""
client.add_user(u)
~~~

Running this scripts shows this output:
~~~
{"username": "guacadmin", "attributes": {"disabled": null, "guac-full-name": null, "valid-from": null, "access-window-end": null, "access-window-start": null, "guac-organizational-role": null, "valid-until": null, "guac-organization": null, "timezone": null, "guac-email-address": null, "expired": null}, "lastActive": 1585956238000}
No handlers could be found for logger "guacapy.client"
Traceback (most recent call last):
  File "./bug.py", line 21, in <module>
    client.add_connection_group(g)
  File "/usr/local/lib/python2.7/dist-packages/guacapy/client.py", line 329, in add_connection_group
    payload=payload
  File "/usr/local/lib/python2.7/dist-packages/guacapy/client.py", line 69, in __auth_request
    r.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: http://host:7070/api/session/data/postgresql-shared/connectionGroups?token=0B478D6FC3362F602DDAFCA59394EE40B28C5CCD1A28E3D1EAC4CE6922F646C0
~~~
docker logs:

~~~
23:21:32.461 [http-nio-8080-exec-1] INFO  o.a.g.r.auth.AuthenticationService - User "guacadmin" successfully authenticated from 10.1.0.146.
23:21:32.552 [http-nio-8080-exec-5] ERROR o.a.g.rest.RESTExceptionMapper - Unexpected internal error: Can not instantiate value of type [simple type, class org.apache.guacamole.rest.connectiongroup.APIConnectionGroup] from JSON String; no single-String constructor/factory method
~~~

Both add_user and add_connection_group fail with the same 500 Server Error.

**Comment by wolfaba** [comment]
Hi,
I got this error too. I have played MITM using socat and could read the request sent by python as plai-text in wireshark and the request looks like:
```POST /api/session/data/postgresql/users?token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX HTTP/1.1
Host: HHHHHHHHHHHHHHHHH:2000
User-Agent: python-requests/2.23.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Content-Length: 228
Content-Type: application/json

"{\"username\":\"UUUUUUUUUUU\",\"password\":\"PPPPPPPPPPP\",\"attributes\":{\"disabled\":\"\",\"expired\":\"\",\"access-window-start\":\"\",\"access-window-end\":\"\",\"valid-from\":\"\",\"valid-until\":\"\",\"timezone\":null}}"
```
From some reason the text has been escaped for using as code in python. I no python programmer but I try to investigate more.
Regards.
Robert.

**Comment by wolfaba** [comment]
OK, I have found the problem.

Following is incorrect:
```
u = """\
{   
    "username": "testusr",
    "password": "testpwd",
    "attributes": {
        "disabled": "",
        "expired": "",
        "access-window-start": "",
        "access-window-end": "",
        "valid-from": "",
        "valid-until": "",
        "timezone": ""
    }
}"""
```
The `u` is defined as a string. Which is incorrect, because this content is processed by `body = complexjson.dumps(json)` which converts the `json` to string. And the `json` must be therefore dictionary:
```
u = {   
    "username": "testusr",
    "password": "testpwd",
    "attributes": {
        "disabled": "",
        "expired": "",
        "access-window-start": "",
        "access-window-end": "",
        "valid-from": "",
        "valid-until": "",
        "timezone": ""
    }
}
```
Using dictionary will generate correctly text representation of JSON.
I could create user with dict structure instead of string.
This issue can be closed.
Regards.
Robert.
